### ISSUE TITLE
gulp failing on new theme

### ISSUE THREAD

**Issue by arun9989** [acquia-pso/cog_tools#30]
I have downloaded this module from this repo and put it my project and generated a theme using `drush gen cog` command. 

In the generated theme folder to run the font-end setup I ran `npm install` and it creates `node_modules` folder within theme. After that when I run `./node_modules/.bin/gulp`, I am getting following error:

```
/var/www/myproject/docroot/themes/custom/mytheme/node_modules/pa11y/lib/pa11y.js:24
async function pa11y(url, options = {}, callback) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at requireFn (/var/www/myproject/docroot/themes/custom/mytheme/node_modules/gulp-load-plugins/index.js:75:14)
```

**Comment by sarahjean** [comment]
@arun9989 Thanks for your report. Can you tell us what version of node and npm you are running? We have been mainly testing against 8, I suspect yours is a bit older or newer.
